---
title: "city-guide"
author: "aune"
format: html
editor: visual
theme: default
---

# Hamburg & Rotterdam City-Guide
## City's crowded places: culture, cafés, and cool stuff
*If you are looking for the very best recommendations for the cities of Hamburg and Rotterdam, you've come to the right place! Exclusive recommendations from students living in both cities will make sure that you don't miss out on the best things to do, see, and eat in Hamburg or Rotterdam.*

This trip to Hamburg/Rotterdam is so **bold** of you

# Hamburg Cinemas and Theatres

## *Cinemas*

**Zeise , Abaton, and Passage** are examples of smaller cinemas with a special selection of (often more political) movies and a beautiful flair.

## *Theatres*

Theatres like **Schauspielhaus, Thalia Theater, Kammerspiele, and Ernst-Deutsch-Theater** all offer impressive plays throughout the year.

# Place to avoid in Hamburg: 
The *main train station* at night
*City centre* on weekends or holidays, it's just too crowded

# Museums and Culture:
*Museum für Kunst und Gewerbe*
*Kunsthalle*

# Café Spot in Hamburg: 
*Lowinskys* - my very favourite place at the moment: lovely café, friendly staff, famous for their good matcha and excellent coffee, also offer bagels, grilled cheese, and baked goods, such as tahini brownies and pistachio cookies. The owner is bringing New York's spirit to Hamburg
website: https://lowinskys.com/

# Hamburger Schietwetter: what to do outside when it's raining dogs and cats in the most beautiful city in Northern Germany 
Going for a walk in the *Jenisch Park* 
Visiting the *Botanischen Garten* 
Taking the *ferry to Finkenwerder* 
Walking through the *Alter Elbtunnel*

# Cool water things to do in Hamburg:
Swimming in the *Dove Elbe*, right outside of the city.
Riding pedal boat in the *Außenalster* right in the middle of the city.
Stand Up *Paddling* is also great.

# Place to relax:
*Kaifu-Bad*, Eimsbüttel
*Roots Yoga Studio* im Grindel, perfect for good yoga sessions and meditation

# The very best spots in Hamburg an Rotterdam - all the places you don't want to miss out on :)


